version: "3.9"

services:
  storage:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "mevdb"
      POSTGRES_USER: "roller"
      POSTGRES_PASSWORD: "roller123"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5433:5432"
